on:
  push:
    branches: main

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Generate semver
      id: version-generator
      run: |
        ARTEFACT_VERSION=$(git describe --long --always | sed -r "s/-(([^-]*-){1}[^-]*)$/.\\1/") 
        echo "{ARTEFACT_VERSION}={$(git describe --long --always | sed -r "s/-(([^-]*-){1}[^-]*)$/.\\1/")}" >> $GITHUB_ENV
        echo "ARTEFACT_VERSION=${ARTEFACT_VERSION}" > src/.env
    - name: Build image
      run: |
        docker build --build-arg Build=${{ env.ARTEFACT_VERSION }} \
        -t klimdos/polybank:${{ env.ARTEFACT_VERSION }} .
        docker tag klimdos/polybank:${{ env.ARTEFACT_VERSION }} \
        klimdos/polybank:latest
    - name: Push image
      run: |
        docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
        docker push klimdos/polybank:${{ env.ARTEFACT_VERSION }}
    - name: send message telegram
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: "${{ env.ARTEFACT_VERSION }}"
